groups:
- name: card_counter
  interval: 10s
  rules:
  - record: card_count
    expr: label_replace( count by(__name__) ({__name__!="", __name__!="card_count"}), "metric_name", "$1", "__name__", "(.+)" )
  - record: card_count:rate5m
    expr: rate(card_count[5m])
